# rename to config.py
COMPUTER_SLACK_TOKEN = 'oDXXXXXXXXXXXXXyp'
COMPUTER_SLACK_OAUTH_ACCESS_TOKEN = 'xoxp-40XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXfd'
COMPUTER_SLACK_BOT_TOKEN = 'xoxb-40XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXQQ'
COMPUTER_GERRIT_DOMAIN = 'gerrit.example.com'